# Generated by Django 6.0.3 on 2026-04-10 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_comment_dislikes_comment_likes_alter_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='dislikes',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='likes',
        ),
    ]
