# Generated by Django 6.0.3 on 2026-04-20 17:20

import api.models
import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_comment_author_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='avatars/default.png', null=True, upload_to=api.models.build_avatar_path),
        ),
    ]
