# Generated by Django 6.0.3 on 2026-04-20 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_profile_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='professor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='professors',
            field=models.ManyToManyField(blank=True, null=True, related_name='disciplines', to='api.professor'),
        ),
    ]
