# Generated by Django 6.0.3 on 2026-04-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_professor_comment_professor_discipline_professors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='professors',
            field=models.ManyToManyField(blank=True, related_name='disciplines', to='api.professor'),
        ),
    ]
