# Generated by Django 6.0.3 on 2026-04-20 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_discipline_professors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discipline',
            name='professors',
        ),
        migrations.AddField(
            model_name='professor',
            name='discipline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professors_list', to='api.discipline'),
        ),
    ]
