# Generated by Django 6.0.3 on 2026-04-20 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_discipline_professors_professor_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.professor'),
        ),
    ]
