# Generated by Django 6.0.3 on 2026-04-20 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_comment_professor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='professor_comments', to='api.professor'),
        ),
    ]
