services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  backend:
    build: ./backend
    working_dir: /app
    env_file:
      - .env
    volumes:
      - ./backend/backend:/app
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    depends_on:
      - db

  nginx:
    image: nginx:latest
    working_dir: /app
    ports: [ "80:80" ]
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/dist/frontend/browser:/var/www/html
    depends_on:
      - backend

    redis:
    image: redis:7-alpine
    container_name: redis_app
    volumes:
      - redis_data:/data
    #ports: ["6379:6379"]
    expose: 
      - 6379
    restart: always
    command: >
     redis-server 
     --appendonly yes
     --appendfsync everysec        
     --requirepass ${REDIS_PASSWORD:-your_password}
     --maxmemory 256mb
     --maxmemory-policy allkeys-lru
   #(AOF (Append Only File))
   #  --save 60 100 (RDB)
   #appendonly.aof

volumes:
  postgres_data:
